port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: global
log-level: info
external-controller: '127.0.0.1:9090'
secret: '233333'
dns:
  enable: true
  ipv6: false
  listen: '127.0.0.1:53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.3
    - 1.0.0.3
  fallback:
    - 'tls://family.cloudflare-dns.com'
    - 'https://family.cloudflare-dns.com/dns-query'
tun:
  enable: true
  stack: gvisor
  auto-route: true
proxies:
  -
    name: '1'
    type: vmess
    server: 42.159.198.36
    port: 20031
    uuid: e8c2ace3-dc64-35f2-b3cc-222c2367fd71
    alterId: 2
    cipher: auto
    udp: true
    network: ws
    ws-path: /
    ws-headers:
      Host: tokyo1.fatboy.monster
    tls: true
  -
    name: '2'
    type: vmess
    server: iepl1-hk.ddns1.pw
    port: 40002
    uuid: e8c2ace3-dc64-35f2-b3cc-222c2367fd71
    alterId: 2
    cipher: auto
    udp: true
  -
    name: '3'
    type: vmess
    server: iepl1-hk.ddns1.pw
    port: 40020
    uuid: e8c2ace3-dc64-35f2-b3cc-222c2367fd71
    alterId: 2
    cipher: auto
    udp: true
  -
    name: '4'
    type: vmess
    server: sd-gg.ddns1.pw
    port: 20004
    uuid: e8c2ace3-dc64-35f2-b3cc-222c2367fd71
    alterId: 2
    cipher: auto
    udp: true
  -
    name: '5'
    type: vmess
    server: sd-gg.ddns1.pw
    port: 20002
    uuid: e8c2ace3-dc64-35f2-b3cc-222c2367fd71
    alterId: 2
    cipher: auto
    udp: true
proxy-groups:
  -
    name: Proxies
    type: select
    proxies:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
rule-providers:
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
rules:
  - RULE-SET,private,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,Proxies
